import AppKit

/// Single source of truth for "must never be recorded" pasteboard content.
///
/// Consumers: ClipboardHistoryStore (clipboard-history feature) and the intent
/// sensors on the thesis branch. One shared list, one shared check — so the two
/// clipboard paths cannot drift apart again (they already had: the intent sensor
/// launched knowing only 2 of these 4 markers).
enum PasteboardPrivacy {

    /// Sensitive / transient markers set by source apps on the pasteboard.
    static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",       // password managers
        "com.apple.is-sensitive",               // Apple secure fields
        "org.nspasteboard.TransientType",       // "do not store"
        "org.nspasteboard.AutoGeneratedType",   // programmatic write, not a user copy
    ]

    /// True when the pasteboard's current types mark its contents as sensitive or
    /// transient — such content must not be recorded, classified, hashed, embedded,
    /// or persisted in ANY derived form.
    static func isSensitive(_ types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types, !types.isEmpty else { return false }
        return !Set(types.map(\.rawValue)).isDisjoint(with: excludedTypes)
    }
}
